### ISSUE TITLE
BTC deposits not reflecting in spendable balance

### ISSUE THREAD

**Issue by Trefz23** [joule-labs/joule-extension#217] opened 2019-06-01 15:11 UTC
### Description of the Issue

Sent BTC to local LND node via 'deposit' tab in browser extension, reflected in 'transactions' tab but not in spendable sat balance. See second tx in screenshot (350k sat)

Note that BTC sent to the node pubkey address (not using Joule browser functionality) posts successfully in my spendable balance. See first tx in screenshot (40k sat)

### Steps to Reproduce

Clicked 'deposit' which generated a new address, sent BTC funds to that address from Coinbase account. 

### Description of Your Setup

*Browser & version*: Chrome
*Operating system*: Mac OS Sierra
*Node software & version*: "version": "0.6.1-beta commit=v0.6.1-beta-21-g863bf2f91b245afd58c8edc078a171a55e48f931". Running LND on a local bitcoind node.

### Console Logs / Screenshots

<img width="406" alt="Screen Shot 2019-06-01 at 11 10 04 AM" src="https://user-images.githubusercontent.com/36718911/58750243-db71bd00-845d-11e9-8d10-0549508e18b9.png">

**Comment by wbobeirne** [comment] 2019-06-01 17:08
Hey @Trefz23, thanks for the issue. Next to your balance you should see a little yellow clock shape. That indicates you have some pending balance, but it's currently unusable because it's waiting for some block confirmations. Those UTXOs should be usable in ~20-60 minutes.

Sorry if this was confusing! I'm going to close this issue out as it's not a bug, but if you have any suggestions on how to better display this, let me know.

**Closed by wbobeirne** 2019-06-01 17:08 UTC

**Comment by Trefz23** [comment] 2019-06-01 18:52
Hey - thanks for the reply.

That transaction was sent yesterday.

**Comment by wbobeirne** [comment] 2019-06-01 19:12
Gotcha, do you still see the yellow clock though? If you click on it, it should give you a breakdown of your balances.

**Comment by Trefz23** [comment] 2019-06-01 19:15
I do, however the 350k transaction isn't represented in the yellow clock breakdown. I haven't spent any UTXOs since I initiated that transaction, and it shows as having 150+ confirmations (txid: 857ceb99a7aadb9e7e7255580530ac62f54b453e4e2815bf9d34821ee22e4aaf).


<img width="398" alt="Screen Shot 2019-06-01 at 3 14 02 PM" src="https://user-images.githubusercontent.com/36718911/58752602-e9d0d080-847f-11e9-9536-26d43ea664a9.png">

**Comment by wbobeirne** [comment] 2019-06-01 19:38
Hmm, very strange. Unfortunately I think you're going to have to ask the LND folks. Joule merely displays what comes back from the LND RPC calls, there're no custom calculations or address inspections going on here.

**Comment by Trefz23** [comment] 2019-06-01 20:07
so when i click 'deposit' in the joule window, it's essentially running a 'getnewaddress' rpc call from my local node?

**Comment by wbobeirne** [comment] 2019-06-01 21:57
Yep, that's all it's doing.

**Comment by wbobeirne** [comment] 2019-06-03 15:33
I had someone else report this, it could be possible this is related to the bug with Bitcoin core 0.18.0. Did you happen to upgrade to that?
